storage: ./verdaccio-storage
auth:
  htpasswd:
    file: ./verdaccio-storage/htpasswd
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
logs:
  - {type: file, path: 'verdaccio.log', format: pretty, level: http}
packages:
  '@bilt/*':
    access: $all
    publish: $all
    proxy: npmjs
  '**':
    proxy: npmjs

