version: 2
jobs:
  build:
    machine:
      image: circleci/classic:latest
    environment:
      CI: 1
    steps:
      - checkout
      - run:
          name: Install node
          command: |
            set +e
            export NODE_VERSION=10.6.0
            echo 'nvm install' ${NODE_VERSION} >> $BASH_ENV
      - run:
          name: Install bilt
          command: npm install -g @bilt/bilt-cli
      - run:
          name: Run bilt
          command: bilt -u @bilt/bilt-cli

