version: 2
jobs:
  build:
    machine:
      image: circleci/classic:latest
    environment:
      CI: 1
    steps:
      - checkout
      - run:
          name: Setup nvm
          command: |
            set +e
            touch $BASH_ENV
            export NODE_VERSION=10.6.0
            echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
            # echo 'nvm install' ${NODE_VERSION} >> $BASH_ENV
      - run:
          name: Install correct Node version
          command: |
            nvm install 10.6.0
            nvm alias default 10.6.0
      - run:
          name: Install bilt
          command: |
              npm install -g @bilt/bilt-cli
      - run:
          name: Bild
          command: bilt -u @bilt/bilt-cli
