version: 2
jobs:
  build:
    machine:
      image: circleci/classic:latest
    environment:
      CI: 1
    steps:
      - checkout
      - run:
          name: Install node
          command: |
            set +e
            touch $BASH_ENV
            export NODE_VERSION=10.6.0
            echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
            echo 'nvm install' ${NODE_VERSION}' >> $BASH_ENV
      - run:
          name: Node Version
          command: |
            nvm use 10
            node --version
